"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()


getEnv = os.getenv

SECRET_KEY =  getEnv('SECRET_KEY')
DEBUG = getEnv('DEBUG')
VIRUSTOTAL_API = getEnv('VIRUSTOTAL_API')
VIRUSTOTAL_URL = getEnv('VIRUSTOTAL_URL')
VIRUSTOTAL_API_KEY = getEnv('VIRUSTOTAL_API_KEY')

BASE_DIR = Path(__file__).resolve().parent.parent

ALLOWED_HOSTS = [
    "*",
    "localhost",
]
# Application definition
THIRD_PARTY_APPS = [
    # 'material',
    # 'material.admin',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

LOCAL_APPS = [
    'virustotal',
    # 'charts',

]

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Adjust this as needed
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


INSTALLED_APPS =  THIRD_PARTY_APPS + DJANGO_APPS + LOCAL_APPS;

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ROOT_URLCONF = 'backend.urls'
WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # POSTGRESS
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': getEnv('DATABASE_NAME'),
    #     'USER': getEnv('DATABASE_USER'),
    #     'PASSWORD': getEnv('DATABASE_PASSWORD'),
    #     'HOST': getEnv('DATABASE_HOST'),
    #     'PORT': getEnv('DATABASE_PORT'),
    #     # 'OPTIONS': {
    #     #     'sslmode': 'require',
    #     #     'sslrootcert': getEnv('DATABASE_SSLROOTCERT'),
    #     # },
    # },
    
    # DJANGO DJONGO MONGO DB ENGINE - not working on latest django
    # 'default': {
    #    'ENGINE': 'djongo',
    #    'NAME': 'vipyrdb',
    #    'ENFORCE_SCHEMA': False,
    #    'CLIENT': {
    #        'host': 'mongodb://localhost:27017',
    #    }
    # },
    
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# settings.py

AUTHENTICATION_BACKENDS = [
   
    'django.contrib.auth.backends.ModelBackend',  # The default backend for other methods (optional)
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Cors
CORS_ORIGIN_ALLOW_ALL = bool(getEnv('CORS_ORIGIN_ALLOW_ALL', False))
CORS_ALLOW_CREDENTIALS = bool(getEnv('CORS_ALLOW_CREDENTIALS', False))
CORS_ALLOW_ALL_ORIGINS = bool(getEnv('CORS_ALLOW_ALL_ORIGINS', False))
# ACCESS_CONTROL_ALLOW_ORIGIN = getEnv('ACCESS_CONTROL_ALLOW_ORIGIN', '*')
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://localhost:8080",
    "http://localhost:5000",
    "https://vipyr-frontend.vercel.app",
]

# Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,

}



MATERIAL_ADMIN_SITE = {
    'HEADER':  'Threat Dashboard',  # Admin site header
    'TITLE':  'Untread',  # Admin site title
    # 'FAVICON':  'path/to/favicon',  # Admin site favicon (path to static should be specified)
    # 'MAIN_BG_COLOR':  'color',  # Admin site main color, css color should be specified
    # 'MAIN_HOVER_COLOR':  'color',  # Admin site main hover color, css color should be specified
    # 'PROFILE_PICTURE':  'path/to/image',  # Admin site profile picture (path to static should be specified)
    # 'PROFILE_BG':  'path/to/image',  # Admin site profile background (path to static should be specified)
    # 'LOGIN_LOGO':  'path/to/image',  # Admin site logo on login page (path to static should be specified)
    # 'LOGOUT_BG':  'path/to/image',  # Admin site background on login/logout pages (path to static should be specified)
    # 'SHOW_THEMES':  True,  #  Show default admin themes button
    # 'TRAY_REVERSE': True,  # Hide object-tools and additional-submit-line by default
    # 'NAVBAR_REVERSE': True,  # Hide side navbar by default
    # 'SHOW_COUNTS': True, # Show instances counts for each model
    # 'APP_ICONS': {  # Set icons for applications(lowercase), including 3rd party apps, {'application_name': 'material_icon_name', ...}
    #     'sites': 'send',
    # },
    # 'MODEL_ICONS': {  # Set icons for models(lowercase), including 3rd party models, {'model_name': 'material_icon_name', ...}
    #     'site': 'contact_mail',
    # }
}

MEDIA = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

UPLOAD_DIR = os.path.join(BASE_DIR, 'uploads')
STATIC_DIR = os.path.join(BASE_DIR, 'static')
