# Generated by Django 5.1.3 on 2024-11-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(unique=True)),
                ('scan_id', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('reputation', models.TextField()),
                ('votes', models.JSONField()),
                ('times_submitted', models.IntegerField()),
                ('last_analysis_stats', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
