# Generated by Django 5.1.3 on 2024-11-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virustotal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyses',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
